"$schema" = "./node_modules/wrangler/config-schema.json"
name = "crashcalproxy"
main = "workers/proxy.ts"
compatibility_date = "2026-03-04"

[[kv_namespaces]]
id = "b4d2428b1de641e0893fe9e0e35f40f0"
binding = "STALE_CALENDAR_ICS"

[observability.logs]
enabled = true